version: 0.0
os: linux

files:
  - source: /
    destination: /opt/nodeapp
    overwrite: true

hooks:
  BeforeInstall:
    - location: codedeploy/scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: codedeploy/scripts/install_deps.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: codedeploy/scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: codedeploy/scripts/validate_service.sh
      timeout: 300
      runas: ec2-user